#!/bin/bash

[[ -n $1 && $1 == "-h" ]] && export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l -g ""'
[[ -n $1 && $1 != "-h" ]] && QUERY="-q $1"

file=$(fzf ${QUERY})
[[ -n ${file} && -f ${file} ]] && ls "${file}" && nvim "${file}"
