#!/bin/bash

command -v bc &>/dev/null || { echo "Command 'bc' not found, please install it and try again" >&2 && exit 1; }
 
trap ctrlC INT

RUN=1
function ctrlC() {
    RUN=0
}

START="$(date '+%s %N')"
iteration=0
while [ "${RUN}" -eq 1 ]; do
    iteration=$((iteration + 1))
    "$@" || break
done
END="$(date '+%s %N')"

startSeconds="$(echo "${START}" | cut -d ' ' -f1)"
endSeconds="$(echo "${END}" | cut -d ' ' -f1)"
startNs="$(echo "${START}" | cut -d ' ' -f2)"
endNs="$(echo "${END}" | cut -d ' ' -f2)"
startMs="$(echo "${startNs} / 1000000" | bc -l)"
endMs="$(echo "${endNs} / 1000000" | bc -l)"

deltaS="$(echo "${endSeconds} - ${startSeconds}" | bc -l)"
deltaMs="$(echo "${endMs} - ${startMs}" | bc -l)"
deltaMsTotal="$(echo "${deltaS} * 1000 + ${deltaMs}" | bc -l)"
delta="${deltaMsTotal}"

deltaSeconds="$(echo "${delta} / 1000" | bc -l)"
averageSpeed="$(echo "${iteration} / ${deltaSeconds}" | bc -l)"

function printFloat() {
    printf "%.3f" "${1}"
}

echo -e "\n-------------------------------------"
[ "${RUN}" -eq 0 ] && echo -e "User interrupted the process by Ctrl+C" || echo "Failed after ${iteration} iterations."

echo -n "The job has ran for "
# Let's output the time in seconds if the overall time exceeds 10 seconds
if (( $(echo "${delta} > 10000" | bc -l) )); then
    printFloat "${deltaSeconds}"
    echo "s"
else
    printFloat "${delta}"
    echo "ms"
fi
echo -n "Average speed: "
printFloat "${averageSpeed}"
echo "/s"

