#!/bin/bash

# MIT License
# 
# Copyright (c) 2020 Marek Bogusovsky
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#function _c() {
#    xrdb -quiet -get "$1" | tr -d '\n'
#}

function toColor() {
    [ "${1:0:1}" == "#" ] && echo -n "${1}" && return 0
    case $1 in
         "0" | "black"        |   "color0")   echo -n '#242933' ;;
         "1" | "red"          |   "color1")   echo -n '#BF6161' ;;
         "2" | "green"        |   "color2")   echo -n '#A3BE8C' ;;
         "3" | "yellow"       |   "color3")   echo -n '#EBCB8B' ;;
         "4" | "blue"         |   "color4")   echo -n '#5E81AC' ;;
         "5" | "magenta"      |   "color5")   echo -n '#BA6FAB' ;;
         "6" | "cyan"         |   "color6")   echo -n '#8FBCBB' ;;
         "7" | "white"        |   "color7")   echo -n '#BBC3D4' ;;
         "8" | "l-black"      |   "color8")   echo -n '#2E3440' ;;
         "9" | "l-red"        |   "color9")   echo -n '#C57272' ;;
        "10" | "l-green"      |   "color10")  echo -n '#B1C89D' ;;
        "11" | "l-yellow"     |   "color11")  echo -n '#EFD49F' ;;
        "12" | "l-blue"       |   "color12")  echo -n '#81A1C1' ;;
        "13" | "l-magenta"    |   "color13")  echo -n '#B786AD' ;;
        "14" | "l-cyan"       |   "color14")  echo -n '#9FC6C5' ;;
        "15" | "l-white"      |   "color15")  echo -n '#D8DEE9' ;;
        *) echo -n "#ff00e0" ;; # error color
    esac
}

function colorize {
  [ "$1" = '-n' ] && FLAGS=("-n") && shift
  echo "${FLAGS[@]}" "<span foreground=\"$(toColor "${1}")\">${2}</span>"
}

function colorizeBegin {
  echo -n "<span foreground=\"$(toColor "${1}")\">"
}

function colorizeEnd {
  echo "$@" "</span>"
}

function interpolateColor {
    color-map "$(toColor "${1}")" "$(toColor "${2}")" "${3}"
}
