#!/bin/bash

# MIT License
#
# Copyright (c) 2026 Marek Bogusovsky
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

MAX_NUMBER_OF_PLAYERS=20

NUMBER_OF_PLAYERS=$(up-scoreboard "28960" | head -n1 | grep "Scoreboard" | grep -Eo "[0-9]+" || echo 0)
FILLED_PERCENTAGE=$(( NUMBER_OF_PLAYERS * 100 / MAX_NUMBER_OF_PLAYERS ))

jq -M --unbuffered --compact-output -n \
    --arg text "${NUMBER_OF_PLAYERS}" \
    --arg alt "${NUMBER_OF_PLAYERS}" \
    --arg tooltip "${NUMBER_OF_PLAYERS}" \
    --arg class "c${FILLED_PERCENTAGE}" \
        '{text: $text, alt: $alt, tooltip: $tooltip, class: $class}'
